# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrushSupport' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrushSupport
  pod 'OneSignal', '~> 1.13.3'

  # Pods for CrushSupport

  target 'CrushSupport-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrushSupportTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CrushSupport-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrushSupport-tvOS
end
